### ISSUE TITLE
Release in apk form 

### ISSUE THREAD

**Issue by oathzed** [adnanjelic/SimpleAndroidTvStreamingApp#1]
Hello,

Curious about your app you're making, :) will you be releasing an apk for us to do testing and report bugs etc.?

**Comment by adnanjelic** [comment]
Hi, thanks for the question.

This is a pet app for showcasing my skills and it is still WIP. There are many more things to be implemented before making this ready for end users.

I did not plan to release an apk, at least for now (if at the end I create something that can be useful for end users then I will publish it).

**Comment by oathzed** [comment]
> Hi, thanks for the question.
> 
> This is a pet app for showcasing my skills and it is still WIP. There are many more things to be implemented before making this ready for end users.
> 
> I did not plan to release an apk, at least for now (if at the end I create something that can be useful for end users then I will publish it).

Ok that makes sense, thank you
